defaults:
  - _self_
  - train: base_train
  - dataset: imagenet
  - info: info
  - model: base_model
  - benchmark: benchmark

name: experiment0

wandb: True
distributed: False
local_rank: 0
world_size: 1
port: 3456
gpus: [ 0 ]
