name: imageNet
root: /data/image_classification/imageNet
size: (3,224,224)
input_size: (3,224,224)

mean: [ 0.485, 0.456, 0.406 ]
std: [ 0.229, 0.224, 0.225 ]
scale: [ 0.08, 1.0 ]

train_name: train
valid_name: validation
test_name: test
class_map:

in_channel: 3
num_classes: 1000