defaults:
  - augmentation: base_augmentation

name: imageNet
root: /data/classification/imageNet

in_channel: 3
num_classes: 1000
size: [ 3,224,224 ]

train: train
valid: validation
test: test
class_map:

augmentation:
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]