defaults:
  - augmentation: base_augmentation

dataset_name: imageNet
name: imageNet
root: /data/imageNet
task: multiclass

in_channels: 3
num_classes: 1000
size: [ 3,224,224 ]

train: train
valid: validation
test: test
class_map:

augmentation:
  mean: [ 0.485, 0.456, 0.406 ]
  std: [ 0.229, 0.224, 0.225 ]

  smoothing: 0.1
  mixup: 0.1
  cumix: 1.0
  crop_pct: 0.95
  aa: rand-m7-mstd0.5-inc1