no_aug: False

mean:
std:

scale: [ 0.08, 1.0 ]
ratio: [ 0.75, 1.33 ]
hflip: 0.5
vflip: 0
color_jitter: 0.4
aa:
crop_pct: 0.875

epoch_repeats: 0
aug_repeats: 0
aug_splits: 0
re:
reprob: 0
remode: pixel
recount: 1
resplit: False

mixup: 0
cutmix: 1.0
cutmix_minmax:
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: batch # [batch | pair | elem]
mixup_off_epoch: 0

smoothing: 0.1
train_interpolation: random # [random, bilinear, bicubic]
test_interpolation: bicubic

worker_seeding: all
pin_mem: True
prefetcher: True
use_multi_epochs_loader: False