defaults:
  - config
  - override train/optimizer: lamb
  - _self_

gpus: [ 0,1 ]
name: a2_resnet50

train:
  epochs: 300
  batch_size: 256
  num_workers: 16
  bce_loss: True
  target_thresh: 0.2

  lr_scheduler:
    warmup_epochs: 5
    warmup_lr: 1e-4
    min_lr: 1e-6
  
  optimizer:
    grad_accumulation: 2


model:
  model_name: resnet50
  drop_path_rate: 0.05

dataset:
  augmentation:
    mixup: 0.1
    cumix: 1.0
    crop_pct: 0.95
    aa: rand-m7-mstd0.5-inc1
    aug_repeat: 3
    remode: pixel
    smoothing: 0.0
