defaults:
  - _self_
  - override train/optimizer: lamb
  - config

gpus: [ 0,1 ]
name: a3_resnet50

train:
  epochs: 100
  batch_size: 224
  num_workers: 8
  bce_loss: True
  target_thresh: 0.2

  lr_scheduler:
    warmup_epochs: 5
    warmup_lr: 1e-4
    min_lr: 1e-6

  optimizer:
    grad_accumulation: 4

model:
  model_name: resnet50
  drop_path_rate: 0.05

dataset:
  augmentation:
    mixup: 0.1
    cumix: 1.0
    crop_pct: 0.95
    aa: rand-m7-mstd0.5-inc1
    aug_repeat: 3
    remode: pixel
    smoothing: 0.0