defaults:
  - config
  - override train/optimizer: lamb
  - override train/lr_scheduler: cosine
  - override dataset: cifar100
  - _self_

gpus: [ 6 ]
name: ${dataset.name}_${model.model_name}

train:
  epochs: 100
  batch_size: 256
  num_workers: 2
  bce_loss: False
  target_thresh: 0.0

  lr_scheduler:
    warmup_epochs: 5
    warmup_lr: 1e-4
    min_lr: 1e-6

  optimizer:
    lr: 3.5e-3
    weight_decay: 1e-3

model:
  model_name: resnet50_cifar
  drop_path_rate: 0.1

dataset:
  augmentation:
    cutmix: 0.0
    mixup: 0.0
    smoothing: 0.1