defaults:
  - config
  - override train/optimizer: lamb
  - override train/lr_scheduler: cosine
  - override dataset: cifar100
  - _self_

gpus: [ 0,1,2,3 ]
name: cifar100

train:
  epochs: 50
  batch_size: 128
  num_workers: 2
  bce_loss: False
  target_thresh: 0.0

  lr_scheduler:
    warmup_epochs: 0
    warmup_lr: 1e-5
    min_lr: 1e-6

  optimizer:
    grad_accumulation: 2
    lr: 3.5e-3

model:
  model_name:
  drop_path_rate: 0.1

dataset:
  augmentation:
    cutmix: 0.0
    mixup: 0.0
    smoothing: 0.1