defaults:
  - _self_
  - set: base_set

hydra:
  run:
    dir: runs/${set.model.model_name}_${set.dataset.name}/${set.name}_${now:%Y%m%d-%H%M%S}/

  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${now:%m-%d}_${now:%H-%M}_${hydra.job.name}_${set.name}.log
    root:
      handlers:
        - console
        - file
    disable_existing_loggers: false