sched: ???

min_lr: 0.
sched_on_update: False

decay_epochs: 30
decay_milestones: [ 30, 60 ]
decay_rate: 0.1

warmup_epochs: 5
warmup_lr: 1e-5
cooldown_epochs: 10
patience_epochs: 10

lr_cycle_mul: 1.
lr_cycle_decay: 0.5
lr_cycle_limit: 1

lr_noise_pct: 0.67
lr_noise_std: 1.
